# Generated by Django 6.0.2 on 2026-02-16 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], default='file', max_length=10)),
                ('file_obj', models.FileField(blank=True, null=True, upload_to='vault/%Y/%m/%d/')),
                ('extension', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('size_bytes', models.BigIntegerField(default=0, editable=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('last_accessed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vault.node')),
            ],
            options={
                'ordering': ['-node_type', 'name'],
                'indexes': [models.Index(fields=['owner', 'parent'], name='vault_node_owner_i_282f48_idx'), models.Index(fields=['is_trashed'], name='vault_node_is_tras_c36f76_idx')],
                'unique_together': {('name', 'parent', 'owner')},
            },
        ),
    ]
