# Generated by Django 6.0.2 on 2026-02-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
